// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaOrderingSystemWebMVC.Models;

namespace PizzaOrderingSystemWebMVC.Migrations
{
    [DbContext(typeof(pizzaContext))]
    [Migration("20210923090257_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DelivaryCharges")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.OrderDetail", b =>
                {
                    b.Property<int>("ItemNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("PizzaNumber")
                        .HasColumnType("int");

                    b.Property<int?>("PizzaNumberNavigationPizzaNumber")
                        .HasColumnType("int");

                    b.HasKey("ItemNumber");

                    b.HasIndex("OrderId");

                    b.HasIndex("PizzaNumberNavigationPizzaNumber");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.OrderItemDetail", b =>
                {
                    b.Property<int>("ItemNumber")
                        .HasColumnType("int");

                    b.Property<int>("ToppingNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ItemNumberNavigationItemNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ToppingNumberNavigationToppingNumber")
                        .HasColumnType("int");

                    b.HasKey("ItemNumber", "ToppingNumber");

                    b.HasIndex("ItemNumberNavigationItemNumber");

                    b.HasIndex("ToppingNumberNavigationToppingNumber");

                    b.ToTable("OrderItemDetails");
                });

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.PizzaDetail", b =>
                {
                    b.Property<int>("PizzaNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PizzaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PizzaPrice")
                        .HasColumnType("int");

                    b.Property<string>("PizzaType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PizzaNumber");

                    b.ToTable("PizzaDetails");
                });

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.Topping", b =>
                {
                    b.Property<int>("ToppingNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ToppingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToppingPrice")
                        .HasColumnType("int");

                    b.HasKey("ToppingNumber");

                    b.ToTable("Toppings");
                });

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.UserLoginDetail", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserAddress")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("User_Address");

                    b.Property<string>("UserMail")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("User_name");

                    b.Property<string>("UserPassword")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("User_password");

                    b.Property<string>("UserPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Phone_No");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B0FBA213F7B4106B");

                    b.ToTable("UserLoginDetails");
                });

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.Order", b =>
                {
                    b.HasOne("PizzaOrderingSystemWebMVC.Models.UserLoginDetail", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.OrderDetail", b =>
                {
                    b.HasOne("PizzaOrderingSystemWebMVC.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId");

                    b.HasOne("PizzaOrderingSystemWebMVC.Models.PizzaDetail", "PizzaNumberNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("PizzaNumberNavigationPizzaNumber");

                    b.Navigation("Order");

                    b.Navigation("PizzaNumberNavigation");
                });

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.OrderItemDetail", b =>
                {
                    b.HasOne("PizzaOrderingSystemWebMVC.Models.OrderDetail", "ItemNumberNavigation")
                        .WithMany("OrderItemDetails")
                        .HasForeignKey("ItemNumberNavigationItemNumber");

                    b.HasOne("PizzaOrderingSystemWebMVC.Models.Topping", "ToppingNumberNavigation")
                        .WithMany("OrderItemDetails")
                        .HasForeignKey("ToppingNumberNavigationToppingNumber");

                    b.Navigation("ItemNumberNavigation");

                    b.Navigation("ToppingNumberNavigation");
                });

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.OrderDetail", b =>
                {
                    b.Navigation("OrderItemDetails");
                });

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.PizzaDetail", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.Topping", b =>
                {
                    b.Navigation("OrderItemDetails");
                });

            modelBuilder.Entity("PizzaOrderingSystemWebMVC.Models.UserLoginDetail", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
